### ISSUE TITLE
Tracking issue for V10

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#235]
Opening this so we can track what's happening.

cc @joeabbey / @faddat / @dimiandre 

As far as possible, these should be done one branch per issue.

- [x] Remove ignite CLI
- [ ] SDK 0.45.7
- [ ] Liquid staking
  - Commonwealth discussion on various options
  - Text prop (yes/no etc) based on outcome of that
  - **PENDING VOTE PASSING:** Iqlusion liquid staking https://github.com/CosmosContracts/juno/issues/234 OR another impl

I am assuming ICQ will be v11 of Juno as there are at least two competing implementations and we will need to make a call on which makes most sense for Juno. If we can decide before then, we can get it into v10.

Probably also v11 of Juno:

- [ ] Token Factory https://github.com/osmosis-labs/osmosis/tree/main/x/tokenfactory
- [ ] ICA - need to revisit #215 once the above two things are done
- [ ] ICS https://github.com/CosmosContracts/juno/issues/233

**Comment by faddat** [comment]
Related Pull requests:

Juno:
* #207 


IBC:
* https://github.com/cosmos/ibc-go/pull/1418
* https://github.com/cosmos/ibc-go/pull/1443
* https://github.com/cosmos/ibc-go/pull/1653
* https://github.com/cosmos/ibc-go/pull/1709
* https://github.com/cosmos/ibc-go/pull/1734
* https://github.com/cosmos/ibc-go/pull/1782

CW:
* https://github.com/CosmWasm/wasmd/pull/912
* https://github.com/CosmWasm/wasmd/pull/873
* https://github.com/CosmWasm/wasmd/pull/863

Interchain Accounts:
* https://github.com/cosmos/interchain-accounts-demo/pull/105

**Comment by faddat** [comment]
Hey, I'd like to propose this as v10:


https://github.com/CosmosContracts/juno/pull/262

**Comment by the-frey** [comment]
Have updated to clarify that v10 will be 0.45.7 not 46

**Comment by the-frey** [comment]
Note: #262 has been merged with non-mainline wasmd.

Before v10 is shipped, we need to wait for wasmd to be updated to work with our changes.
