### ISSUE TITLE
Fee share module refactor

### ISSUE THREAD

**Issue by vuong177** [CosmosContracts/juno#412]
## Background
The problem in fee share module https://github.com/CosmosContracts/juno/pull/385 : 
 - We shouldn't use fork auth for antehandler. It breaks the SDK design. I think we should refactor the logic in ante and remove the fork auth. 
 - GRPC query method : we should reuse the existing [gogo protobuf] instead of use custom method.
 - We have a lot of unused code, and unused interface :
	- We have an `AccountKeeper` interface but never use
	- Func `NewHandler` has never been used it
	- Same with `accountKeeper`  in feeshare Keeper struct. 
	- FeeSharePayoutDecorator` use feegrantkeeper and authkeeper but never use ?  We need to make the code clean for easier maintenance.  

- A lot of functions in keeper file aren't covered by the test.
- In `GetSigned()` implementation, we shouldn't create panic by MustAccAddressFromBech32.

## Suggested Design

- [x] Refactor ante handler in feeshare module. https://github.com/CosmosContracts/juno/issues/413
- [x] Reuse the existing [gogo protobuf] instead of use custom method  **https://github.com/CosmosContracts/juno/issues/414**
- [x]  Add more tests for the FeeShare module, coverage function in keeper https://github.com/CosmosContracts/juno/issues/415
- [x] Remove unused code https://github.com/CosmosContracts/juno/issues/416
- [ ] Should we get a better iterator for query ? https://github.com/CosmosContracts/juno/issues/417
- [ ] #433

**Comment by faddat** [comment]
Great progress here
