### ISSUE TITLE
Tracking issue for v13

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#475]
Juno v13 has these changes:

- [x] https://github.com/CosmosContracts/juno/issues/334
  - [x] #368 
- [x] https://github.com/CosmosContracts/juno/pull/312
- [x] #385
- [x] https://github.com/CosmosContracts/juno/pull/329
- [x] #314 
- [x] https://github.com/CosmosContracts/juno/issues/280

I'd like to get these in too:

* https://github.com/CosmosContracts/juno/pull/392
* https://github.com/CosmosContracts/juno/pull/390
* https://github.com/CosmosContracts/juno/pull/388
* https://github.com/CosmosContracts/juno/pull/391
* https://github.com/CosmosContracts/juno/pull/393

As well as:

* [x] https://github.com/CosmosContracts/juno/pull/387 + IBCFees (If it breaks uni we revert IBCFee middleware)
* [x] https://github.com/CosmosContracts/juno/pull/385 (which we're definitely testing out, if it were to break uni then we'd remove it from v13)

**Comment by faddat** [comment]
I disagree about IBC test, and think it should be removed from the v13 roadmap.

**Comment by the-frey** [comment]
2023-02-06

Current slated v13 has diverged:

- [ ] Packet Forward Middleware
- [ ] Feeshare
- [ ] Token Factory

+ Remove intertx

Further discussion needed on 0.30 of wasmd if available because of IBC fees & IBC v4, i.e these are 

- [ ] IBC v4
- [ ] 0.30 wasmd
- [ ] Token Factory -> IBC v4
- [ ] IBC Fee

Looking forward to v14, we also expect to get in

- [ ] IBC hooks (from Osmosis, but these need permissioning)

**Comment by nicolaslara** [comment]
>  IBC hooks (from Osmosis, but these need permissioning)

IIUC, the `wasmkeeper.NewDefaultPermissionKeeper` defaults to permissionless. It checks the params to see who is authorised to upload/instantiate, and the default is "Everybody":

`junod q wasm params --node https://rpc.juno.kingnodes.com:443`

```
code_upload_access:
  address: ""
  addresses: []
  permission: Everybody
instantiate_default_permission: Everybody
```

Am I missing something @the-frey ?

**Comment by Reecepbcups** [comment]
@nicolaslara We are going to prioritize this for v14, will keep you updated

**Comment by Reecepbcups** [comment]
Successful launch :partying_face: Onto v14 now
