### ISSUE TITLE
Tracking issue for v14

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#548]
List of features we are looking into for Juno V14

## Native Features
- [x] https://github.com/CosmosContracts/juno/pull/615
- [x] https://github.com/CosmosContracts/juno/pull/591
- [x] [GlobalFee](https://github.com/CosmosContracts/juno/pull/597)
- [x] [Permissionless IBC hook ](https://github.com/CosmosContracts/juno/pull/597)
- [x] Replace E2E with InterchainTest
- [x] https://github.com/CosmosContracts/juno/pull/613
- [x] https://github.com/CosmosContracts/juno/pull/587

# Other
- [x] https://github.com/CosmosContracts/juno/pull/601
- [x] https://github.com/CosmosContracts/juno/pull/600

**Comment by faddat** [comment]
I'd love to have globalfee

**Comment by 0xekez** [comment]
having IBC callbacks would be nice because it would let us use ICA from smart contracts: https://github.com/cosmos/ibc-go/blob/aditya/adr-008/docs/architecture/adr-008-app-caller-cbs/adr-008-app-caller-cbs.md

**Comment by Reecepbcups** [comment]
@0xekez It seems its still in design / idea phase of the ADR. - This likely won't be possible to get in for v14 unless someones already implemented elsewhere. 

Ill add to our longer term tracker though and maybe transition to me doing some IBC work

**Comment by 0xekez** [comment]
@Reecepbcups , thanks! I was just talking with them today, and it seems like it may be in soon enough for 14, though only time will tell. Just want to put it on your radar as that's whats blocking DAO DAO from using interchain accounts.
