### ISSUE TITLE
Interchain-test: Tracking Issue v1

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#610]
# TODO
- [x] Add TokenFactory (https://github.com/CosmosContracts/juno/pull/663)
- [x] FeeShare Test (https://github.com/CosmosContracts/juno/pull/668)
- [x] Unity Gov Contract (https://github.com/CosmosContracts/juno/pull/669)
- [ ] State Sync test
- [ ] GlobalFee test
- [ ] Cosmwasm 1.1 and 1.2 features
- [ ] Stargate Queries (all)
- [ ] #657 (https://github.com/CosmosContracts/juno/pull/678)
- [ ]  https://github.com/CosmosContracts/juno/issues/682

ictest wasm CI example: https://github.com/Reecepbcups/cw-work-journal

**Comment by Reecepbcups** [comment]
Greatly improved. While not every task here has been completed, the most important + some where done. Closing, will do on a case by case need basis.
