### ISSUE TITLE
Tracking Issue for future roadmap

### ISSUE THREAD

**Issue by reecepbcups** [CosmosContracts/juno#611]
This is a long term tracking solution to put future wants / needs for long term development. 

## TODO
- [ ] Optimistic Block Commits
- [ ] Lowering unbonding time (requires IBC channel upgrades, much testing)
- [ ] Babylon chain (Lower unbonding after testing with ictest. If failures, see if we can patch upstream)
- [ ] mesh Security Consumer
- [ ] https://github.com/CosmosContracts/juno/issues/474
- [x] [IBC Callbacks for ICA with contracts](https://github.com/cosmos/ibc-go/blob/aditya/adr-008/docs/architecture/adr-008-app-caller-cbs/adr-008-app-caller-cbs.md) (IBC v7.3)
- [x] WasmClient for Juno<->Polkadot IBC connection
- [x] Smart contract begin / end blockers (Half done with x/clock)

## Faster Faster block times
- [x]  JUNO Blocks @ 3s
- [x] https://github.com/CosmosContracts/juno/pull/634
- [x] [CosmosCache distribution](https://github.com/Reecepbcups/cosmos-endpoint-cache)

## Migrate Core-1 Vesting
- [x] https://github.com/CosmosContracts/juno/pull/741

Tendermint ideas for <2s blocks:
- increase signing window
- Only save val signing state if a block sign is missed within the signing window
- If a vals state is not in a signing, then it signed. If false, we explicitly tell this. This drastically reduces space. Or just reuse the actual signatures
- If the val set changes, we save all bools for every val this once to update it (like a cache) for future new val misses
- Improve p2p tendermint connections
- UDP vs TCP for P2P? (keep it TCP for block data / mempool, just UDP for actual connections)
