### ISSUE TITLE
v16 Tracking Issue

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#650]
SDK v47 upgrade & migrations 

# TODO
- [x] https://github.com/CosmosContracts/juno/issues/697
- [x] https://github.com/CosmosContracts/juno/issues/610
- [x] ICQ from StrangeLove
- [x] https://github.com/CosmosContracts/juno/pull/730
- [x] https://github.com/CosmosContracts/juno/pull/708
- [x] https://github.com/CosmosContracts/juno/pull/707
- [x] https://github.com/CosmosContracts/juno/pull/706
- [x] https://github.com/CosmosContracts/juno/pull/705
- [x] https://github.com/CosmosContracts/juno/pull/692
- [x] https://github.com/CosmosContracts/juno/pull/689
- [x] https://github.com/CosmosContracts/juno/pull/690
- [x] Wasm based oracle (OjO)

**Comment by Reecepbcups** [comment]
COMPLETED WOOOO!
