### ISSUE TITLE
Moneta Mainnet Release Checklist

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#87]
~In order to call the Moneta upgrade complete, we need to do the following:~

~- Gov prop to set block max gas #82~
~-  Moneta alpha upgrade #71 #72~
~- Moneta beta upgrade #17 #85~

~Once moneta is up, we will want to pin some contracts, to reduce their cost. This is via governance. ~

~- Contract pinning gov prop~

~Some example contracts that might be pinned:~

~- DAODAO~
~- JunoMint~
~- Junoswap~
~- whoami~
~etc...~

~This will be followed by a final release:~

~- Replace wasmd fork with wasmd 0.21 when SDK 44 <-> wasmd is complete and audited~

___________________________

### New working plan:

- [x] Gov prop to set block max gas #82 
- [x] Test a single `moneta` upgrade that includes #71 #72 #17 #85 #90 and #95 on a testnet
- [x] Gov prop for `moneta` upgrade on mainnet
- [x] Do the single `moneta` upgrade on mainnet

Once moneta is up, we will want to pin some contracts. This is done via governance. 

- [ ] Contract pinning gov prop

Some example contracts that might be pinned:

- DAODAO
- JunoMint
- Junoswap
- whoami
- CW20
- CW721
etc...

This will be followed by a final release:

- [x] Replace wasmd fork with wasmd 0.21 when SDK 44 <-> wasmd is complete and audited

**Comment by faddat** [comment]
Little note on wasmd. 

This has proven a bit trick and I'm still on it over the weekend.  I think that these updates are high priority because of some of the recently discovered issues.

**Comment by faddat** [comment]
Hi, given what I've seen recently (Sentinel, Regen) I'd like to recommend that we include the following in Moneta, and recommend it rather strongly.

* ibc-go -> 2.0 (this means writing protocol negotiation for cosmwasm in wasmd)
* tendermint -> 0.35 (this means a refactored and more secure p2p)


I am taking this in phases.  Right now I am doing the module migration process for wasmd, so that it'll have no changes other than the sdk upgrade.  I think our mileage may vary.  But when that is done I'll make a PR with that to the main CW repo.

So my phase one gets us to:

* TM 0.34.14
* SDK 0.44.3
* IBC-go v1.2.3

If it takes too long, and it might, this is probably okay for moneta, but I do prefer the above route.

**Comment by the-frey** [comment]
I think naively that phase one would be adequate, as the 44.3 <-> wasmd / wasmvm security patch is really the biggest thing concerning me atm. Want to be in the position where when the Confio official ver comes out we can switch over pretty seamlessly.

**Comment by faddat** [comment]
I'm trying to write the confio official version

**Comment by faddat** [comment]
https://github.com/notional-labs/wasmd/tree/ibc-go-migration

**Comment by the-frey** [comment]
New working plan:

- [ ] Gov prop to set block max gas #82 
- [ ] Test a single `moneta` upgrade that includes #71 #72 #17 #85 on `uni` testnet
- [ ] Gov prop for upgrade on mainnet
- [ ] Do the single `moneta` upgrade on mainnet

Once moneta is up, we will want to pin some contracts. This is done via governance. 

- [ ] Contract pinning gov prop

Some example contracts that might be pinned:

- DAODAO
- JunoMint
- Junoswap
- whoami
- CW20
- CW721
etc...

This will be followed by a final release:

- [ ] Replace wasmd fork with wasmd 0.21 when SDK 44 <-> wasmd is complete and audited

**Comment by giansalex** [comment]
should we revert this pull #51? 
keplr supports sdk 0.44 with a new feature `no-legacy-stdTx`

**Comment by the-frey** [comment]
just so I understand - keplr supports 0.44 only if legacy is disabled?

**Comment by giansalex** [comment]
`no-legacy-stdTx` is for cosmos-sdk 0.44x chains,  /txs is not necessary.

**Comment by the-frey** [comment]
hmm, yeah well if we can remove unneeded code then that's code we don't need to maintain in future - so I would vote for that

**Comment by surferryan** [comment]
Gas should be set @ 7.5/2100
Adjust for 5% slippage
Adjustment for 10% taxation of net withdrawal.

**Comment by giansalex** [comment]
we can pin codes, after DAODAO launch?

**Comment by the-frey** [comment]
I think we can yeah

**Comment by blockcreators** [comment]
> I think we can yeah

Can we close this issue now?
